!!!!
Program alaphband
implicit none
integer:: q_num,mode_num,i,j,k
real,allocatable ::qpath(:)
real,allocatable ::frequency(:,:)
open(unit=1,File='K3BrO_disp.bands') !!!! phono_freq file generated by the scfph calculation
open(unit=3,File='alaph_band.dat')
write(*,*)"Input q-point_number and mode_number with space as intevel:"
read(*,*)q_num,mode_num
allocate(qpath(q_num))
allocate(frequency(q_num,mode_num))

read(1,*)
read(1,*)
read(1,*)
do i=1,q_num
  read(1,*)qpath(i),(frequency(i,j),j=1,mode_num)
end do

do j=1,mode_num
 do i=1,q_num
  write(3,'(2F20.10)')qpath(i),frequency(i,j)
 end do
  write(3,*)
end do

end program

