!!!!
Program scfphband
implicit none
integer:: q_num,mode_num,tem_num,i,j,k
real::pass_row
real,allocatable ::qpath(:)
real,allocatable ::frequency(:,:,:)
open(unit=1,File='K3BrO_scfph.scph_bands') !!!! phono_freq file generated by the scfph calculation
open(unit=3,File='scfph_band.dat')
write(*,*)"Input temperature_nummber, q-point_number, and mode_number with space as intevel:"
read(*,*)tem_num,q_num,mode_num
allocate(qpath(q_num))
allocate(frequency(tem_num,q_num,mode_num))

read(1,*)
read(1,*)
read(1,*)
do i=1,tem_num
 do j=1,q_num
  read(1,*)pass_row,qpath(j),(frequency(i,j,k),k=1,mode_num)
 end do
 read(1,*)
end do

do k=1,mode_num
 do j=1,q_num
  write(3,'(30F20.10)')qpath(j),frequency(:,j,k)
 end do
  write(3,*)
end do

end program

